# Generated by Django 5.0.1 on 2024-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category_blog_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
